// tetrapod protocol file, requires tetrapod main file to have been loaded first

TP.register("response", "Tetrapod", "ERROR", 1, 1);
TP.register("response", "Tetrapod", "SUCCESS", 1, 2);

TP.registerConst("Tetrapod", "Core", "UNADDRESSED", 0);
TP.registerConst("Tetrapod", "Core", "TYPE_TETRAPOD", 1);
TP.registerConst("Tetrapod", "Core", "TYPE_SERVICE", 2);
TP.registerConst("Tetrapod", "Core", "TYPE_ADMIN", 3);
TP.registerConst("Tetrapod", "Core", "TYPE_CLIENT", 4);
TP.registerConst("Tetrapod", "Core", "TYPE_ANONYMOUS", 5);
TP.registerConst("Tetrapod", "Core", "STATUS_STARTING", 1);
TP.registerConst("Tetrapod", "Core", "STATUS_PAUSED", 2);
TP.registerConst("Tetrapod", "Core", "STATUS_GONE", 4);
TP.registerConst("Tetrapod", "Core", "STATUS_BUSY", 8);
TP.registerConst("Tetrapod", "Core", "STATUS_OVERLOADED", 16);
TP.registerConst("Tetrapod", "Core", "STATUS_FAILED", 32);
TP.registerConst("Tetrapod", "Core", "STATUS_STOPPING", 64);
TP.registerConst("Tetrapod", "Core", "ENVELOPE_HANDSHAKE", 1);
TP.registerConst("Tetrapod", "Core", "ENVELOPE_REQUEST", 2);
TP.registerConst("Tetrapod", "Core", "ENVELOPE_RESPONSE", 3);
TP.registerConst("Tetrapod", "Core", "ENVELOPE_MESSAGE", 4);
TP.registerConst("Tetrapod", "Core", "ENVELOPE_BROADCAST", 5);
TP.registerConst("Tetrapod", "Core", "ENVELOPE_PING", 6);
TP.registerConst("Tetrapod", "Core", "ENVELOPE_PONG", 7);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_BOOLEAN", 1);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_BYTE", 2);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_INT", 3);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_LONG", 4);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_DOUBLE", 5);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_STRING", 6);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_STRUCT", 7);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_BOOLEAN_LIST", 8);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_BYTE_LIST", 9);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_INT_LIST", 10);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_LONG_LIST", 11);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_DOUBLE_LIST", 12);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_STRING_LIST", 13);
TP.registerConst("Tetrapod", "TypeDescriptor", "T_STRUCT_LIST", 14);
TP.registerConst("Identity", "Identity", "IDENTITY_EMAIL", 1);
TP.registerConst("Identity", "Identity", "IDENTITY_DEVICE", 2);
TP.registerConst("Identity", "Identity", "IDENTITY_FACEBOOK", 3);
TP.registerConst("Identity", "Identity", "IDENTITY_TWITTER", 4);
TP.registerConst("Identity", "Identity", "IDENTITY_OAUTH", 5);
TP.registerConst("Identity", "User", "PROPS_DEVELOPER", 1);
TP.registerConst("Identity", "User", "PROPS_ADMIN_T1", 2);
TP.registerConst("Identity", "User", "PROPS_ADMIN_T2", 4);
TP.registerConst("Identity", "User", "PROPS_ADMIN_T3", 8);
TP.registerConst("Identity", "User", "PROPS_ADMIN_T4", 16);
TP.registerConst("Identity", "User", "PROPS_BANNED_T1", 32);
TP.registerConst("Identity", "User", "PROPS_BANNED_T2", 64);
TP.registerConst("Identity", "User", "PROPS_BANNED_T3", 128);

TP.register("request", "BaseService", "Pause", 2, 14690004);
TP.register("request", "BaseService", "Unpause", 2, 10620319);
TP.register("request", "BaseService", "Shutdown", 2, 8989182);
TP.register("request", "BaseService", "Restart", 2, 4802943);
TP.register("request", "BaseService", "ServiceIcon", 2, 4420572);
TP.register("response", "BaseService", "ServiceIcon", 2, 13828744);
TP.register("struct", "Tetrapod", "Core", 1, 9088168);
TP.register("struct", "Tetrapod", "RequestHeader", 1, 7165109);
TP.register("struct", "Tetrapod", "ResponseHeader", 1, 675609);
TP.register("struct", "Tetrapod", "MessageHeader", 1, 11760427);
TP.register("struct", "Tetrapod", "ServerAddress", 1, 14893956);
TP.register("struct", "Tetrapod", "Entity", 1, 10171140);
TP.register("struct", "Tetrapod", "Subscriber", 1, 16013581);
TP.register("struct", "Tetrapod", "WebRoute", 1, 4890284);
TP.register("struct", "Tetrapod", "TypeDescriptor", 1, 6493266);
TP.register("struct", "Tetrapod", "StructDescription", 1, 9642196);
TP.register("request", "Tetrapod", "Register", 1, 10895179);
TP.register("response", "Tetrapod", "Register", 1, 13376201);
TP.register("request", "Tetrapod", "ClusterJoin", 1, 8294880);
TP.register("response", "Tetrapod", "ClusterJoin", 1, 8947508);
TP.register("request", "Tetrapod", "Unregister", 1, 3896262);
TP.register("request", "Tetrapod", "Publish", 1, 3171651);
TP.register("response", "Tetrapod", "Publish", 1, 2698673);
TP.register("request", "Tetrapod", "RegistrySubscribe", 1, 2572089);
TP.register("request", "Tetrapod", "RegistryUnsubscribe", 1, 6168014);
TP.register("request", "Tetrapod", "ServicesSubscribe", 1, 7048310);
TP.register("request", "Tetrapod", "ServicesUnsubscribe", 1, 11825621);
TP.register("request", "Tetrapod", "ServiceStatusUpdate", 1, 4487218);
TP.register("request", "Tetrapod", "AddServiceInformation", 1, 14381454);
TP.register("message", "Tetrapod", "Entity", 1, 10913291);
TP.register("message", "Tetrapod", "ClusterMember", 1, 1076508);
TP.register("message", "Tetrapod", "EntityRegistered", 1, 1454035);
TP.register("message", "Tetrapod", "EntityUnregistered", 1, 14101566);
TP.register("message", "Tetrapod", "EntityUpdated", 1, 3775838);
TP.register("message", "Tetrapod", "TopicPublished", 1, 6873263);
TP.register("message", "Tetrapod", "TopicUnpublished", 1, 6594504);
TP.register("message", "Tetrapod", "TopicSubscribed", 1, 1498241);
TP.register("message", "Tetrapod", "TopicUnsubscribed", 1, 6934832);
TP.register("message", "Tetrapod", "EntityListComplete", 1, 15616758);
TP.register("message", "Tetrapod", "ServiceAdded", 1, 15116807);
TP.register("message", "Tetrapod", "ServiceRemoved", 1, 1629937);
TP.register("message", "Tetrapod", "ServiceUpdated", 1, 1658756);
TP.register("message", "Tetrapod", "ServiceStats", 1, 469976);
TP.register("request", "Identity", "Login", 4, 8202985);
TP.register("response", "Identity", "Login", 4, 16389615);
TP.register("request", "Identity", "Logout", 4, 3999326);
TP.register("request", "Identity", "ModifyIdentity", 4, 7124244);
TP.register("request", "Identity", "Create", 4, 6552804);
TP.register("response", "Identity", "Create", 4, 5348608);
TP.register("request", "Identity", "Link", 4, 15857496);
TP.register("response", "Identity", "Link", 4, 14285084);
TP.register("request", "Identity", "Info", 4, 14709500);
TP.register("response", "Identity", "Info", 4, 3624488);
TP.register("request", "Identity", "UpdateProperties", 4, 1362696);
TP.register("request", "Identity", "GetOrCreateId", 4, 4704002);
TP.register("response", "Identity", "GetOrCreateId", 4, 275166);
TP.register("request", "Identity", "GetAuthSecret", 4, 7311132);
TP.register("response", "Identity", "GetAuthSecret", 4, 378568);
TP.register("struct", "Identity", "Identity", 4, 12701893);
TP.register("struct", "Identity", "User", 4, 10894876);
