#!/bin/sh

main() {
   set -e

   mvn='/usr/local/apache-maven/apache-maven-3.2.1/bin/mvn'
   
   getPropertiesValue build.dir
   BUILD_DIR=$PROP_VALUE

   getPropertiesValue cluster.dir   
   CLUSTER_DIR=$PROP_VALUE

   getPropertiesValue git.dir   
   GIT_DIR=$PROP_VALUE
   
   setBuildNumber

   OUT_DIR=$BUILD_DIR/$BUILD_NUM
   LOG=$OUT_DIR/build.log

   mkdir -p $OUT_DIR
   date | tee $LOG
   echo "\nStarting build $BUILD_NUM" | tee -a $LOG

   echo "\nCore: git update\n---" | tee -a $LOG
   cd $GIT_DIR/core
   git pull >> $LOG 2>&1

   echo "\nPrivate: git update\n---" | tee -a $LOG
   cd $GIT_DIR/private
   git pull >> $LOG 2>&1

   echo "\nPrivate: maven package\n---" | tee -a $LOG
   cd $GIT_DIR/private/build
   $mvn clean package >> $LOG 2>&1

   cp $GIT_DIR/core/*/target/*distrib.zip $OUT_DIR
   cp $GIT_DIR/private/services/*/target/*distrib.zip $OUT_DIR
   touch $OUT_DIR/SUCCESS

   echo "\nBuild successful! See $LOG for details.\n" | tee -a $LOG
   date | tee -a $LOG

}

setBuildNumber() {
   local file=$BUILD_DIR/build.number
   if [ -e $file ]
   then
      BUILD_NUM=`cat $file`
   else
      BUILD_NUM=0
   fi
   BUILD_NUM=$((BUILD_NUM+1))
   echo $BUILD_NUM > $file
}

getPropertiesValue() {
   local prop=$1
   local myDir=$( cd "$( dirname "$0" )" && pwd )

   PROP_VALUE=`grep $prop $myDir/cluster.properties | cut -d= -f2-`
}

main
