#!/bin/sh

main() {
   set -e

   if [ $# -lt 2 ]
   then
      echo "usage: clean olderThan {BUILD_NUM}"
      return 0
   fi

   if [ "$1" != "olderThan" ]
   then
      echo "usage: clean olderThan {BUILD_NUM}"
      return 0
   fi

   getPropertiesValue build.dir
   BUILD_DIR=$PROP_VALUE

   getPropertiesValue cluster.dir   
   CLUSTER_DIR=$PROP_VALUE

   buildNum=$2

   for f in $BUILD_DIR/*
   do
      clean $buildNum $f
   done
   
   for f in $CLUSTER_DIR/*/*
   do
      clean $buildNum $f
   done
   

}

clean() {
   buildNum=$1
   file=$2
   num=`basename $file`
   
   case $num in
     ''|*[!0-9]*) bad=true ;;
     *) echo rm -rf $file ;;
   esac
}

getPropertiesValue() {
   local prop=$1
   local myDir=$( cd "$( dirname "$0" )" && pwd )

   PROP_VALUE=`grep $prop $myDir/cluster.properties | cut -d= -f2-`
}

main $@
